### ISSUE TITLE
HTTP request to Vaultwarden API fails

### ISSUE THREAD

**Issue by mi-skam** [sirtoobii/vaultwarden_ldap_sync#9]
The startup of the service fails right at the API call of Vaultwarden. I double-checked the ADMIN_TOKENs correctness, so Im not sure what else to try.

<details><summary>Debug-Log from Portainer</summary>
<p>

2024-11-05:18:24:50 WARNING [LdapConnector.py] One of returned objects missing your LDAP_EMAIL_ATTR

2024-11-05:18:24:50 DEBUG [LdapConnector.py] LDAP request object returned following keys: dict_keys(['objectClass', 'cn', 'sn', 'givenName', 'distinguishedName', 'instanceType', 'whenCreated', 'whenChanged', 'displayName', 'uSNCreated', 'memberOf', 'uSNChanged', 'name', 'objectGUID', 'userAccountControl', 'codePage', 'countryCode', 'homeDirectory', 'homeDrive', 'pwdLastSet', 'primaryGroupID', 'profilePath', 'objectSid', 'accountExpires', 'sAMAccountName', 'sAMAccountType', 'userPrincipalName', 'objectCategory', 'dSCorePropagationData', 'lastLogonTimestamp'])

2024-11-05:18:24:50 WARNING [LdapConnector.py] One of returned objects missing your LDAP_EMAIL_ATTR

2024-11-05:18:24:50 DEBUG [LdapConnector.py] LDAP request object returned following keys: dict_keys(['objectClass', 'cn', 'sn', 'userCertificate', 'givenName', 'initials', 'distinguishedName', 'instanceType', 'whenCreated', 'whenChanged', 'displayName', 'uSNCreated', 'uSNChanged', 'company', 'name', 'objectGUID', 'userAccountControl', 'codePage', 'countryCode', 'homeDirectory', 'homeDrive', 'pwdLastSet', 'primaryGroupID', 'profilePath', 'objectSid', 'accountExpires', 'sAMAccountName', 'sAMAccountType', 'userPrincipalName', 'lockoutTime', 'objectCategory', 'dSCorePropagationData', 'lastLogonTimestamp', 'msExchUMDtmfMap', 'msExchRecipientSoftDeletedStatus', 'msExchPreviousRecipientTypeDetails', 'msExchWhenMailboxCreated', 'msExchDelegateListBL'])

2024-11-05:18:24:50 WARNING [LdapConnector.py] One of returned objects missing your LDAP_EMAIL_ATTR

2024-11-05:18:24:50 DEBUG [LdapConnector.py] LDAP request object returned following keys: dict_keys(['objectClass', 'cn', 'sn', 'userCertificate', 'givenName', 'initials', 'distinguishedName', 'instanceType', 'whenCreated', 'whenChanged', 'displayName', 'uSNCreated', 'uSNChanged', 'company', 'name', 'objectGUID', 'userAccountControl', 'codePage', 'countryCode', 'homeDirectory', 'homeDrive', 'pwdLastSet', 'primaryGroupID', 'profilePath', 'objectSid', 'accountExpires', 'sAMAccountName', 'sAMAccountType', 'userPrincipalName', 'lockoutTime', 'objectCategory', 'dSCorePropagationData', 'lastLogonTimestamp', 'msExchUMDtmfMap', 'msExchRecipientSoftDeletedStatus', 'msExchPreviousRecipientTypeDetails', 'msExchWhenMailboxCreated', 'msExchDelegateListBL'])

2024-11-05:18:24:50 WARNING [LdapConnector.py] One of returned objects missing your LDAP_EMAIL_ATTR

2024-11-05:18:24:50 DEBUG [LdapConnector.py] LDAP request object returned following keys: dict_keys(['objectClass', 'cn', 'sn', 'userCertificate', 'givenName', 'distinguishedName', 'instanceType', 'whenCreated', 'whenChanged', 'displayName', 'uSNCreated', 'uSNChanged', 'company', 'name', 'objectGUID', 'userAccountControl', 'codePage', 'countryCode', 'homeDirectory', 'homeDrive', 'pwdLastSet', 'primaryGroupID', 'objectSid', 'accountExpires', 'sAMAccountName', 'sAMAccountType', 'userPrincipalName', 'lockoutTime', 'objectCategory', 'dSCorePropagationData', 'lastLogonTimestamp', 'msExchUMDtmfMap', 'msExchRecipientSoftDeletedStatus', 'msExchPreviousRecipientTypeDetails', 'msExchWhenMailboxCreated'])

2024-11-05:18:24:50 WARNING [LdapConnector.py] One of returned objects missing your LDAP_EMAIL_ATTR

2024-11-05:18:24:50 DEBUG [LdapConnector.py] LDAP request object returned following keys: dict_keys(['objectClass', 'cn', 'sn', 'givenName', 'distinguishedName', 'instanceType', 'whenCreated', 'whenChanged', 'displayName', 'uSNCreated', 'memberOf', 'uSNChanged', 'name', 'objectGUID', 'userAccountControl', 'codePage', 'countryCode', 'pwdLastSet', 'primaryGroupID', 'objectSid', 'accountExpires', 'sAMAccountName', 'sAMAccountType', 'userPrincipalName', 'objectCategory', 'dSCorePropagationData'])

2024-11-05:18:24:50 INFO [sync.py] Starting...

2024-11-05:18:24:50 INFO [sync.py] DRYRUN: True

2024-11-05:18:24:50 INFO [sync.py] LDAP server: LDAPSERVER

2024-11-05:18:24:50 INFO [sync.py] Vaultwarden url: PUBLIC-URL

2024-11-05:18:24:50 DEBUG [connectionpool.py] Starting new HTTPS connection (1): PUBLIC-URL:443

2024-11-05:18:24:50 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "GET /admin/users HTTP/11" 404 None

2024-11-05:18:24:50 ERROR [sync.py] Something went wrong. Error: Request returned unexpected return code expected: 200 actual: 404

</p>
</details>

**Comment by mi-skam** [comment]
UPDATE: I had a typo in a env variable. Now one step further.

```shell
2024-11-05:18:43:06 DEBUG [connectionpool.py] Starting new HTTPS connection (1): PUBLIC-URL:443

2024-11-05:18:43:06 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "GET /admin/users HTTP/11" 401 4814

2024-11-05:18:43:06 DEBUG [VaultwardenConnector.py] Could not authenticate using cookie, trying token

2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "POST /admin HTTP/11" 200 None

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Authentication using token successful, storing cookie

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Cookie store found, loading

2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "GET /admin/users HTTP/11" 401 4814

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Could not authenticate using cookie, trying token

2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "POST /admin HTTP/11" 200 None

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Authentication using token successful, storing cookie

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Cookie store found, loading

2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "GET /admin/users HTTP/11" 401 4814

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Could not authenticate using cookie, trying token

2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "POST /admin HTTP/11" 200 None

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Authentication using token successful, storing cookie

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Cookie store found, loading

2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "GET /admin/users HTTP/11" 401 4814

2024-11-05:18:43:07 DEBUG [VaultwardenConnector.py] Could not authenticate using cookie, trying token

2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "POST /admin HTTP/11" 429 4972

2024-11-05:18:43:07 ERROR [sync.py] Something went wrong. Error: Could not authenticate against https://PUBLIC-URL//admin: Unauthorized




```

**Comment by sirtoobii** [comment]
> 2024-11-05:18:43:07 DEBUG [connectionpool.py] https://PUBLIC-URL:443 "GET /admin/users HTTP/11" 401 4814

`PUBLIC_URL` is most likely not a resolvable domain name ;)

**Comment by mi-skam** [comment]
Of course not :)

**Comment by sirtoobii** [comment]
Got it - this is just to not disclose information - but anyways, the token seems to be alright (hence the line `Authentication using token successful, storing cookie` ) however, further attempts fail. 
What version of Vaultwarden are you using?

**Comment by mi-skam** [comment]
Here is my Stack:

```yaml
services:
  vaultwarden_ldap_sync:
    image: vaultwarden_ldap_sync:1.0
    container_name: vaultwarden_ldap_sync
    restart: unless-stopped
    environment:
      LDAP_SERVER: ${VWLDAPSYNC_LDAP_SERVER}
      LDAP_BIND_DN: ${VWLDAPSYNC_LDAP_BIND_DN}
      LDAP_BIND_PW: ${VWLDAPSYNC_LDAP_BIND_PW}
      LDAP_SEARCH_FILTER: ${VWLDAPSYNC_LDAP_SEARCH_FILTER}
      LDAP_BASE_DN: ${VWLDAPSYNC_LDAP_BASE_DN}
      LDAP_EMAIL_ATTR: ${VWLDAPSYNC_LDAP_EMAIL_ATTR}
      LDAP_SCHEME: ${VWLDAPSYNC_LDAP_SCHEME}
      VAULTWARDEN_URL: ${VWLDAPSYNC_VAULTWARDEN_URL}
      VAULTWARDEN_ADMIN_TOKEN: ${VWLDAPSYNC_VAULTWARDEN_ADMIN_TOKEN}
      SQLITE_DB: ${VWLDAPSYNC_SQLITE_DB}
      UNTIE_RE-ENABLED_USERS: ${VWLDAPSYNC_UNTIE_RE-ENABLED_USERS}
      CLEANUP_VANISHED_USERS: ${VWLDAPSYNC_CLEANUP_VANISHED_USERS}
      MAX_USERS_AT_ONCE: ${VWLDAPSYNC_MAX_USERS_AT_ONCE}
      SYNC_INTERVAL_SECONDS: ${VWLDAPSYNC_SYNC_INTERVAL_SECONDS}
      LOGFILE: ${VWLDAPSYNC_LOGFILE}
      LOGLEVEL: ${VWLDAPSYNC_LOGLEVEL}
      DRYRUN: ${VWLDAPSYNC_DRYRUN}
    volumes:
      - vaultwarden_ldap_sync-data:/data
  vaultwarden:
    image: vaultwarden/server:1.32.0-alpine
    container_name: vaultwarden
    restart: unless-stopped
    environment:
      ADMIN_TOKEN: ${VW_ADMIN_TOKEN}
      SIGNUPS_ALLOWED: ${VW_SIGNUPS_ALLOWED}
    volumes:
      - vaultwarden-data:/data
    ports:
      - ${VW_HTTP_PORT_MAP}
volumes:
  vaultwarden_ldap_sync-data:
  vaultwarden-data:
  ```
